{% set name = "alibabacloud-credentials" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2b71ab30745267abd524d64fbe063f7e02649da2ab6daaf1eec05733b7f9c8f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - alibabacloud-credentials-api <2.0.0,>=1.0.0
    - python >={{ python_min }}
    - alibabacloud-tea >=0.4.0
    - aiofiles >=22.1.0,<25.0.0
    - alibabacloud_credentials_api >=1.0.0,<2.0.0
    - apscheduler >=3.10.0,<4.0.0

test:
  imports:
    - alibabacloud_credentials
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aliyun/credentials-python
  summary: The alibabacloud credentials module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
