{% set name = "alibabacloud-credentials" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_credentials-{{ version }}.tar.gz
  sha256: ad065ec95921eaf51939195485d0e5cc9e0ea050282059c7d8bf74bdb5496177

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - alibabacloud-tea >=0.3.9

test:
  imports:
    - alibabacloud_credentials
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aliyun/credentials-python
  summary: The alibabacloud credentials module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
